### Get Tract Centers

```{r}
library(tidyverse)
library(tigris)
library(sf)

center_tr10 <- read_csv("https://www2.census.gov/geo/docs/reference/cenpop2010/tract/CenPop2010_Mean_TR.txt") %>%
    mutate(
        gridid = str_c(STATEFP, COUNTYFP, TRACTCE),
        glat = LATITUDE,
        glon = LONGITUDE
    ) %>%
    mutate(
        glandsea = st_as_sf(., coords = c("LONGITUDE", "LATITUDE"), crs = 4326)  %>%
            st_intersects(st_transform(states(cb = TRUE), crs = 4326), sparse = FALSE) %>%
            {rowSums(.) > 0L}
    ) %>%
    select(gridid, glat, glon, glandsea)
```

```{r}
source("data-raw/03-calculate_closest_distance.R")
source("data-raw/05-calc_windmodel_data.R")
source("data-raw/08-idw_precip.R")
```

### NC - Matthew 2016

```{r}
states_fips <- c("37")
neighbor_states <- c("GA", "NC", "SC", "TN", "VA")
storm_id <- "Matthew-2016"

# get centers
center_tr10_selected <- center_tr10 %>%
    filter(str_sub(gridid, 1, 2) %in% states_fips)

Matthew16 <- list()
Matthew16$closest_dis_tr10 <- calc_closest_dist(storm_id, center_tr10_selected)
Matthew16$windmodel_tr10 <- calc_windmodel_data(storm_id, center_tr10_selected)
Matthew16$prcp_tr10 <- calc_idw_pred(neighbor_states, center_tr10_selected, storm_id, 12)
```

### TX, LA - Harvey 2017

```{r}
states_fips <- c("48", "22")
neighbor_states <- c("NM", "CO", "OK", "AR", "MS", "TX", "LA")
storm_id <- "Harvey-2017"

# get centers
center_tr10_selected <- center_tr10 %>%
    filter(str_sub(gridid, 1, 2) %in% states_fips)

Harvey17 <- list()
Harvey17$closest_dis_tr10 <- calc_closest_dist(storm_id, center_tr10_selected)
Harvey17$windmodel_tr10 <- calc_windmodel_data(storm_id, center_tr10_selected)
Harvey17$prcp_tr10 <- calc_idw_pred(neighbor_states, center_tr10_selected, storm_id, 12)
```

### NC - Florence 2018

```{r}
states_fips <- c("37")
neighbor_states <- c("GA", "NC", "SC", "TN", "VA")
storm_id <- "Florence-2018"

# get centers
center_tr10_selected <- center_tr10 %>%
    filter(str_sub(gridid, 1, 2) %in% states_fips)

Florence18 <- list()
Florence18$closest_dis_tr10 <- calc_closest_dist(storm_id, center_tr10_selected)
Florence18$windmodel_tr10 <- calc_windmodel_data(storm_id, center_tr10_selected)
Florence18$prcp_tr10 <- calc_idw_pred(neighbor_states, center_tr10_selected, storm_id, 12)
```

### Output Data

```{r}
storms <- list(
    "Matthew16" = Matthew16, 
    "Harvey17" = Harvey17, 
    "Florence18" = Florence18) 

dir.create("output")
names(storms) %>%
    walk(function (storm) {
        tables <- names(storms[[storm]])
        dir.create(str_c("output/", storm))
        walk(tables, function (table) {
            print(storms[[storm]][[table]])
            write_csv(storms[[storm]][[table]], str_c("output/", storm, "/", table, ".csv"))
            
        })
    })
```

```{r}
stormEvents <- read_csv("https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2007_c20240216.csv.gz") 

stormEvents %>%
     count(EVENT_TYPE) %>% View()
```

### SVI

```{r}
SVI_year <- 2016

SVI <- str_c("https://svi.cdc.gov/Documents/Data/", SVI_year, "/csv/states/SVI_," SVI_year, "_US.csv")
```